### ISSUE TITLE
How to use different features

### ISSUE THREAD

**Issue by prinshul** [aidos-lab/mantra#14]
The example in the notebook is on "Random node features".

How can we use, "Degree Transform" "Degree Transform Onehot" features.

Thanks.

**Comment by rballeba** [comment]
The features used to perform learning in the paper are computed using the transformations provided in the `[mantra-benchmarks](https://github.com/aidos-lab/mantra-benchmarks/blob/e25eb5505f2c61e3571875b2ec60f4ccedc823e3/code/datasets/transforms.py)` repo. There, you have the degree as well as the random features transforms to obtain the features we used.

**Comment by prinshul** [comment]
Thank you
