### ISSUE TITLE
Add hosted documentation

### ISSUE THREAD

**Issue by Pseudomanifold** [aidos-lab/mantra#7]
Let's add hosted documentation of the API but also of the data to this repository. We can build something already around the current `README.md` but it would be good to document the data loader in more detail. On my side, I'd also like to contribute more documentation providing more information about the data.

**Comment by ErnstRoell** [comment]
I have added the hosted documentation using pydoc, eventually switching to sphinx might be an idea as it gives more flexibility. 
If there is an option to have a subdomain added to the aidos website we can also provide a custom url to have the docs hosted under the aidos domain. 

For adding documentation that would be great! Either in form of a pull request or directly to the main branch is fine.
